name: Build for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # - name: Setup .NET
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: 8.0

      - name: Publish for Windows (x64)
        run: dotnet publish -r win-x64 -c Release --self-contained -p:UseAppHost=true

      - name: Archive Build (x64)
        run: |
          mkdir -p release
          Compress-Archive -Path Champion.Desktop/bin/Release/net8.0/win-x64/publish/* -DestinationPath release/win-x64.zip

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/win-x64.zip
          asset_name: win-x64.zip
          tag: latest
          overwrite: true
