name: Build for macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [osx-x64, osx-arm64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.112

      - name: Restore Dependencies
        run: dotnet restore

      - name: Publish for macOS (${{ matrix.arch }})
        run: dotnet publish -r ${{ matrix.arch }} -c Release --self-contained -p:UseAppHost=true

      - name: Archive Build (${{ matrix.arch }})
        run: |
          mkdir -p release
          zip -r release/macOS-${{ matrix.arch }}.zip Champion.Desktop/bin/Release/net8.0/${{ matrix.arch }}/publish
          ls -lh release

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/macOS-${{ matrix.arch }}.zip
          asset_name: macOS-${{ matrix.arch }}.zip
          tag: latest
          overwrite: true
          file_glob: true