name: Build for macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [osx-x64, osx-arm64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.112

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Publish for macOS (${{ matrix.arch }})
        run: dotnet publish -r ${{ matrix.arch }} -c Release --self-contained -p:UseAppHost=true

      - name: Upload Build Artifact (${{ matrix.arch }})
        uses: actions/upload-artifact@v4
        with:
          name: macOS-${{ matrix.arch }}-build
          path: Champion.Desktop/bin/Release/net8.0/${{ matrix.arch }}/publish
          compression-level: 9

      - name: Upload Build Archive to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          release_name: "Latest macOS Builds"
          draft: false
          prerelease: false
          files: release/macOS-${{ matrix.arch }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
